<?php

/**
 * Implements hook_menu().
 */
function main_menu()
{

    $items['main'] = array(
        'title' => 'Main page',
        'page callback' => 'main_page_content',
        'access callback' => TRUE,
        'menu_name' => 'main',
        'file' => 'main.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );


    $items['page_not_found'] = array(
        'title' => '404 page',
        'page callback' => 'page_not_found',
        'access callback' => TRUE,
        'menu_name' => 'page_not_found',
        'file' => 'main.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );

    $items['access_denied'] = array(
        'title' => '403 page',
        'page callback' => 'access_denied',
        'access callback' => TRUE,
        'menu_name' => 'access_denied',
        'file' => 'main.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );
    return $items;
}